name: Add Issues to Project

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'enhancement') || contains(github.event.issue.labels.*.name, 'feature') || contains(github.event.issue.labels.*.name, 'bug')
    
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/jaodsilv/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}

  set-priority-field:
    runs-on: ubuntu-latest
    needs: add-to-project
    if: contains(github.event.issue.labels.*.name, 'critical') || contains(github.event.issue.labels.*.name, 'high') || contains(github.event.issue.labels.*.name, 'medium') || contains(github.event.issue.labels.*.name, 'low')
    
    steps:
      - name: Set priority based on labels
        uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/users/jaodsilv/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          item-id: ${{ github.event.issue.node_id }}
          field-keys: Priority
          field-values: |
            ${{ 
              contains(github.event.issue.labels.*.name, 'critical') && 'Critical' ||
              contains(github.event.issue.labels.*.name, 'high') && 'High' ||
              contains(github.event.issue.labels.*.name, 'medium') && 'Medium' ||
              contains(github.event.issue.labels.*.name, 'low') && 'Low' ||
              'Medium'
            }}

  set-phase-field:
    runs-on: ubuntu-latest
    needs: add-to-project
    if: contains(github.event.issue.labels.*.name, 'phase-1') || contains(github.event.issue.labels.*.name, 'phase-2') || contains(github.event.issue.labels.*.name, 'phase-3') || contains(github.event.issue.labels.*.name, 'phase-4') || contains(github.event.issue.labels.*.name, 'phase-5')
    
    steps:
      - name: Set phase based on labels
        uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/users/jaodsilv/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          item-id: ${{ github.event.issue.node_id }}
          field-keys: Type
          field-values: |
            ${{ 
              contains(github.event.issue.labels.*.name, 'phase-1') && 'Phase 1: Foundation' ||
              contains(github.event.issue.labels.*.name, 'phase-2') && 'Phase 2: State Management' ||
              contains(github.event.issue.labels.*.name, 'phase-3') && 'Phase 3: Core Features' ||
              contains(github.event.issue.labels.*.name, 'phase-4') && 'Phase 4: Advanced Features' ||
              contains(github.event.issue.labels.*.name, 'phase-5') && 'Phase 5: Polish' ||
              'General'
            }}